### ISSUE TITLE
Module version mismatch 

### ISSUE THREAD

**Issue by miscbits** [w1nk/node-odbc#100]
I've been getting this error and I have no clue how to fix it. I've updated everything to the latest version and Im still getting this error. 

> $ npm install odbc@latest 

I have npm version 3.7.3 and I have node.js version 4.3.1

```
Uncaught Error: Module version mismatch. Expected 47, got 46.
module.(anonymous function) @   ATOM_SHELL_ASAR.js:159
Module._extensions..node    @   module.js:450
module.(anonymous function) @   ATOM_SHELL_ASAR.js:159
Module.load @   module.js:356
Module._load    @   module.js:313
Module.require  @   module.js:366
require @   module.js:385
bindings    @   /Users/miscbits/Projects/sqlMarathon/node_modules/bindings/bindings.js:76
(anonymous function)    @   /Users/miscbits/Projects/sqlMarathon/node_modules/odbc/lib/odbc.js:18
Module._compile @   module.js:425
Module._extensions..js  @   module.js:432
Module.load @   module.js:356
Module._load    @   module.js:313
Module.require  @   module.js:366
require @   module.js:385
(anonymous function)    @   script.js:1
```

**Comment by willfarrell** [comment]
My colleague is running into this on issue on window. Did you find a fix?

**Comment by miscbits** [comment]
unfortunately not. we wound up deciding to not use node since its socket libraries were not as sophisticated as we were hoping. Sorry and good luck

**Comment by wankdanker** [comment]
I'm curious about the references to ATOM_SHELL_ASAR in the stack trace. Was this error in an attempt to use odbc from the context of atom the editor?

**Comment by miscbits** [comment]
I was actually building an electron app.

**Comment by wankdanker** [comment]
@miscbits, @willfarrell  I just checked this real quick (never built an electron app before)...

I installed the electron quick start app and then modified it to use odbc@latest. It worked. 

But, then I used nvm to change my node version to 4.3.1, rebuild and I received this error message. I then added `console.log(process.version)` to the electron app and could see that internally electron was using node v5.10.0. When it worked successfully, I was using node v5.10.1.

So, this makes sense. odbc has to be built using the same version of node that electron is using internally otherwise there are probably breaking ABI differences.

Hope this helps.

**Comment by miscbits** [comment]
That does help. I just checked the version of node in electron and in my machine and found they were different versions. In the future, it seems like this error can come about with all packages, and it wasn't really an error that was specific to this one. I am guessing right now that if I were to just update electron often I wouldn't encounter this issue. 

I don't plan on making any more electron apps anytime soon though so Im not too concerned about it. Thank you for helping to clear that up though.

**Comment by wankdanker** [comment]
@miscbits, I agree that this is potential issue with any module which has a compile step. It seems that electron would have their own package manager that helps keep things in sync.

Glad I could help clear that up.

@willfarrell, were you able to work through this issue?

**Comment by willfarrell** [comment]
Waiting for my colleague to get in to ask. Thanks for the quick replies.

**Comment by willfarrell** [comment]
Looks like his error is a little different, but same first line.

**Comment by wankdanker** [comment]
@willfarrell, Module version mismatch errors definitely have to do with the odbc module being built for a different version of node than the version of node that is trying to run the code. `npm rebuild` might help.

**Comment by TheCyberRonin** [comment]
I've had that issue, but found a fix. I didn't look at the issues until now. Here is what I did, hopefully it works out or gets you pointed in the right direction.
It'll add another dependency, but if you use a packager you can prune the dev dependencies.
Make a .npmrc file that will detail what version of Electron you are trying to build for (I was building a 32 bit app), you can remove target_arch line if you are using the same arch as the machine you are building on.

```
runtime = electron
target = 1.4.0
target_arch = ia32
dist_url = https://atom.io/download/atom-shell
```

Then install node-gyp and electron rebuild modules to be able to rebuild odbc for electron

```
npm install -D node-gyp --production windows-build-tools
npm install -D electron-rebuild
```

You would only need to do that to add them to the dev dependencies of package.json
**_After every change to your node_modules folder, do_** `electron-rebuild <directory of app>`
@willfarrell @miscbits

**Comment by miscbits** [comment]
Thanks for the answer. I wound up dropping this project but will keep this in mind in the future since it seems like its a problem that commonly comes up.
