### ISSUE TITLE
Invalid string or buffer length

### ISSUE THREAD

**Issue by minusplusminus** [w1nk/node-odbc#101]
Hi everyone,

I'm currently using your library and looking at the possibilities of it. 

I'm using an ODBC connection of King software (king.eu). I've tested if it's working in Microsoft Excel using Microsoft query to check if I can retreive data. It works and I want to do the same using Nodejs. The ODBC connection is based on an iAnywhere driver. 

I used this code:

```
function openConnection(query)
    {
    var login = "DRIVER={King 5.53a};DBQ=C:\Quadrant\King\Data\DemoFin.db;UID="+user+";PWD="+password+";DATABASE="+dbname;
    console.log(login);
    db.open(login, function(err)
    {
        if (err) {
        //Something went bad
        console.log(err);

        //Let's not go any further
        return;
        }


        db.query(query, function(err, rows, moreResultSets)
        {
            //console.log(err);
            if (err) {
                //Something went bad
                console.log(err);
                console.log(util.inspect(rows));
                 db.close(function(){});
                //Let's not go any further
                return;
            }


            console.log(util.inspect(rows));
            console.log(moreResultSets);
            db.close(function(){});
        });
    });
```

What i receive are table data with an undefined value. This is the error I get:

`[Error: [Sybase][ODBC Driver]Invalid string or buffer length]
  errors: 
   [ { message: '[Sybase][ODBC Driver]Invalid string or buffer length',
       state: 'HY090' } ],
  error: '[node-odbc] Error in ODBC::GetColumnValue',
  message: '[Sybase][ODBC Driver]Invalid string or buffer length',
  state: 'HY090' }
`
I've tried to change it to UTF8, but failed. 

Kind regards

**Comment by minusplusminus** [comment]
Fixed it by disabling unicode

**Comment by p-hebert** [comment]
@minusplusminus you are a saver ❤️

**Comment by sergiu79** [comment]
> Fixed it by disabling unicode

How exactly did you do that? I am having similar issue

**Comment by p-hebert** [comment]
Check here => https://github.com/wankdanker/node-odbc#unicode
