### ISSUE TITLE
Build error when the UNICODE define is removed from binding.gyp

### ISSUE THREAD

**Issue by markbnc** [w1nk/node-odbc#118]
In my use case, I need to remove the UNICODE binding to use node-odbc.  When I do this with version 1.4.0, I get the following build error

../src/odbc_connection.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCConnection::GetInfoSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/odbc_connection.cpp:1182:52: warning: the address of ‘userName’ will always evaluate as ‘true’ [-Waddress]
         info.GetReturnValue().Set(Nan::New(userName).ToLocalChecked());
                                                    ^
../src/odbc_connection.cpp:1182:54: error: ‘Nan::imp::FactoryBase<v8::Boolean>::return_t {aka class v8::Local<v8::Boolean>}’ has no member named ‘ToLocalChecked’
         info.GetReturnValue().Set(Nan::New(userName).ToLocalChecked());

In my local build, I modified the line referenced above to 
         
          info.GetReturnValue().Set(Nan::New<v8::String>((const char *) userName).ToLocalChecked());

that fixed the build and calling db.conn.getInfoSync(47) returned the name of the user the connection was established with.

**Comment by wankdanker** [comment]
@markbnc: thank you for reporting this and for the code sample.

Fix published to npm as odbc@1.4.1. 

Thank you for your contribution. Please reopen this issue if it is not resolved in the patch release.

**Comment by markbnc** [comment]
Confirmed that this if fixed in the 1.4.1 release

Thanks
