### ISSUE TITLE
Date Parsing with DB2 driver

### ISSUE THREAD

**Issue by radiodario** [w1nk/node-odbc#18]
First of all, thanks for these bidings, they are proving incredibly useful.

I'm using odbc version 0.3.1 (as installed from npm)

I'm encountering difficulties parsing TIMESTAMPS coming from a IBM DB2 driver:

> var res = []; db2.queryDB('select eventdate from dev.trace_table order by EVENTDATE desc fetch first row only with ur', function(results) { res = results });
> undefined
> res
> [ { EVENTDATE: Sun, 07 Dec 1969 09:03:09 GMT } ]

When I run the same query on isql i get the correct results i.e 

SQL> select eventdate from dev.trace_table order by EVENTDATE desc fetch first row only with ur
+---------------------------+
| EVENTDATE                 |
+---------------------------+
| 2012-04-05 07:30:19.160547|
+---------------------------+
SQLRowCount returns -1
1 rows fetched

**Comment by radiodario** [comment]
I forgot to mention that the db2.queryDB function is just a wrapper: 

exports.queryDB = function(sql, callback) {
        var db = new odbc.Database();
        db.open("DSN=DATABASE;UID=dario;PWD=somepass", function(err)
        {
                if (err) {
                        //Something went bad
                        console.log(err);
                        //Let's not go any further
                        return;
                }
                db.query(sql, function (error, result, info) {
                        if (error) {console.log(error); return false;}
                        callback(result);
                });

```
    });
```

}

**Comment by radiodario** [comment]
I was able to fix this issue by casting to double before multiplication

tuple->Set(String::New((const char *)columns[i].name), Date::New(double(mktime(&timeInfo)) \* 1000 ));

**Comment by wankdanker** [comment]
Hey @radiodario, Thanks for the report. I'll try out your fix to make sure it doesn't break MSSQL and anything else I can try. I'm glad you were able to get that working.

**Comment by radiodario** [comment]
thanks!

**Comment by w1nk** [comment]
Dan - if you can send me a pull req, I'll go ahead and merge it in.  I'll find you on irc later today also!
