### ISSUE TITLE
Error handling when issuing a query

### ISSUE THREAD

**Issue by wankdanker** [w1nk/node-odbc#2]
In EIO_Query we check to see if SQLExecDirect succeeded or failed. If it failed, should we:

Emit('result', ... )  immediately and somehow cancel the EIO_AfterQuery?

or

Save the error to prep_req and Emit('result', ... ) from EIO_AfterQuery including the error, a null recordset and false moreRecordSets?

Also, should there be an Emit('error') somewhere so that we can have a handler on the javascript side to receive callbacks for errors? I don't think I would use this, but still wondering.

Dan

**Comment by w1nk** [comment]
I think if we want to follow the normal node conventions, emitting result with an err object filled up to the callback is probably the way to go.  I like the idea of being able to emit an error globally though, so maybe both? :).  What do you think?

**Comment by wankdanker** [comment]
I think both is probably the way to go. I will work on this. Can you think of anything else that should be returned in the error object other than whatever error details can be determined and the original sql statement?

**Comment by wankdanker** [comment]
Just closing this issue. I implemented the global error emit and the node convention of callback(error, []). I figured it would be best to return the error and an empty array. That way we can ignore the error and always check data.length rather than having to check if data && data.length.
