### ISSUE TITLE
Fetch all rows as Array of Arrays

### ISSUE THREAD

**Issue by terma-tec** [w1nk/node-odbc#24]
Please, I think it's really necessary to let user fetch ALL results as Array of Arrays instead of Array of Objects,
because to convert from Array of Arrays to Array of Objects is very simple,
could be done by each user and it will work fast,
but to convert from Array of Objects to Array of Arrays will work not so quick,
and should be done by native code...

**Comment by w1nk** [comment]
terma-tec, I think what you're saying is instead of this:

[{ column : value, column2: value2} , { column : value, column2: value2}]

You'd want an option to get this:

[ [value, value2], [value,value2] ]

Am I understanding that correctly?

**Comment by terma-tec** [comment]
Yes sure,

Array of arrays is easier to handle in many situations, it would be helpful
if you can return array of arrays natively from the library (optimized and
compiled), because to convert it will take some processor time for big
arrays...
I wrote a function on javascript, but I'm worry it will work slow...

function to_cols_and_rows( rows_of_objects ) {
if (rows_of_objects.length<1) return [[],[]];
var cols = Object.keys( rows_of_objects[0] );
var rors = rows_of_objects.map( function(row) {
return cols.map( function(col) { return row[col] } )
});
return [ cols, rows ];
}

Anyway it's not critical but I think it would be good to have this option...
In other libraries (for example ruby freetds it's possible to specify in
what format I want to recieve rows array, arrah of hash objects or array of
arrays)...

Anyway thanks for reply!

2012/7/19 w1nk <
reply@reply.github.com

> terma-tec, I think what you're saying is instead of this:
> 
> [{ column : value, column2: value2} , { column : value, column2: value2}]
> 
> You'd want an option to get this:
> 
> [ [value, value2], [value,value2] ]
> 
> Am I understanding that correctly?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/w1nk/node-odbc/issues/24#issuecomment-7110289

## 

Eugene Piatenko
Director

TERMA TRAVEL TECHNOLOGIES s.r.o.
Kolma 834/40, 360 01 Karlovy Vary
Czech Republic

Tel: +420 739 388830
Tel: +380 50 3000688
Skype: piatenko
Email: piatenko@terma-tec.com

**Comment by w1nk** [comment]
I think that should be easy enough to do.  I'll keep this open and roll it into the next release.  wankdanker and I were waiting for the node build system to stabilize enough to go ahead and fix up a windows port.  I think that's likely happened by now so we should probably get the wheels turning again :).

**Comment by wankdanker** [comment]
I have a working implementation of this on my [v0.4-arrayish](https://github.com/wankdanker/node-odbc/tree/v0.4-arrayish) branch. It is definitely not final and I'm not comfortable with two things:
- the call back function has a lot of args: `cb(err, data, moreRecordSets, columns)`
- I don't think it would be nice to just change the objects returned by the `query()` method as it will break existing code [of mine].
  - we could have one method, `.queryArray()` which will return the array as @terma-tec suggested
  - `.query()` will have to build up an array of objects on the JavaScript side
  - we could have the cpp side of things aware of `queryArray()` or `query()` and return the proper Array from cpp.

**Comment by w1nk** [comment]
What do you think about having a property attached to the db object that will flag which behavior query() should use?  We could still keep 2 methods internally in the c++ side of things, and call the proper one based on the property.

**Comment by wankdanker** [comment]
We could do that. I feel weird about having two separate methods in c++ doing what `Database::UV_AfterQuery` does. Which is where we either create the array of arrays or the array of objects. I feel like the logic within `Database::UV_AfterQuery` should be aware of the behavior flag and execute the callback appropriately. 

I'm not sure the best way to go about doing that because I wouldn't want to have a large number of if/then statements choosing between `tuple->Set(keyName,...)` and `values->Set(arrayIndex,...)`. 

It would be pretty easy to just get the value of the column (`Number::New(atof(buf))`, `Date::New(double(mktime(&timeInfo)) * 1000)`, `String::New(buf)`, etc) and store it in a temporary variable and then have one if statement at the end of processing the column. I just don't know what type of variable I should use to store any other of those types.

**Comment by wankdanker** [comment]
Seems like `Local<Value> value;` might work to hold different data types. Well, at least it works with String and kinda works with Boolean. Modifying tests to use as many types as possible.

**Comment by w1nk** [comment]
Looks like that'd do it,  http://bespin.cz/~ondras/html/classv8_1_1Value.html

We can detect the type as well (if need be) and retrieve it accordingly.

**Comment by wankdanker** [comment]
Just a quick note, when creating the array of objects on the JavaScript side the qps drops by about 2k. And that silly bench in only returning 1 column. So, we do need to do it on the c++ side, imo.

**Comment by wankdanker** [comment]
This is done as of v0.5.12. Proper usage would be something like this:

``` javascript
var odbc = require('odbc')
   , db = odbc({ fetchMode : odbc.FETCH_ARRAY })
   ;

db.open(connectionString, function (err) {
  db.queryResult('select 1 as test, 2 as anotherTest', function (err, result) {
    //if you need to get column names as an array...
    var cols = result.getColumnNamesSync();

    //fetch
    result.fetchAll(function (err, rows) {
      console.log(rows);
      //[ [ 1, 2 ] ]
    });
  });
});
```

If you don't care about getting the column names then it is simpler...

``` javascript
var odbc = require('odbc')
   , db = odbc({ fetchMode : odbc.FETCH_ARRAY })
   ;

db.open(connectionString, function (err) {
  db.query('select 1 as test, 2 as anotherTest', function (err, rows) {
      console.log(rows);
      //[ [ 1, 2 ] ]
  });
});
```
