### ISSUE TITLE
Can not install on windows, no waf, can you compile it to windows ?

### ISSUE THREAD

**Issue by orenz** [w1nk/node-odbc#25]

**Comment by wankdanker** [comment]
This is something that has been discussed, but I don't currently have a windows development environment to work on this. Not sure if @w1nk does either. Patches welcome.

**Comment by orenz** [comment]
ODBC is cool and important, however, if not  on windows,  it will be very
limited.
All U need is to compile, like all top modules did.
I can not help, I do not know how, and too busy to learn now.

**Comment by wankdanker** [comment]
You could try installing [node-gyp](https://github.com/TooTallNate/node-gyp/) (npm install -g node-gyp), python 2.7, Visual C++ Express, then download and extract https://github.com/wankdanker/node-odbc/zipball/v0.4.1. Then try running node-gyp configure build in the extracted directory. If it works then yeah, all we need to do is compile. If not, then we need to debug and implement platform specific changes.

It currently fails on my system, but that may be because the windows system I have access to can not be rebooted at the moment and the Visual C++ install can't complete as a result.

I do have a use case for this on Windows coming up, so this may be something I will be working on more in the near future.

**Comment by w1nk** [comment]
Oren,

   As Dan said, we should be circling up soon to get a windows build
functional.  I do have a build environment, I just lack time at the
moment.  That should be changing in the next few weeks and I'll get with
Dan and we'll see where we're at.  I'd expect there to be a little porting
involved, but not tons.  For instance we use pthread's mutex mechanisms,
we'll need to support using the win32 semaphores as a substitute on win32.
All in all though, it should be a pretty straightforward port as the root
of this code base was initially a win32 library anyhow.

-Lee

**Comment by orenz** [comment]
Thanks,

I will be waiting.

I think ODBC is the best way to work.
you learn only one API and use it for all databases.

**Comment by jeffwillden** [comment]
+1 to get odbc running cross-platform. I develop on Mac, deploy on both Windows and *nix servers. Cross-platform modules are nearly essential for my projects.

**Comment by orenz** [comment]
Tried compiling on windows got a few errors.

**Comment by wankdanker** [comment]
Great news, I have successfully built this on Windows and it works. There is only one issue which is that Windows does not have a `strptime()` function. Hopefully, I will be able to get everything updated in the next few days.

**Comment by orenz** [comment]
Great !!! waiting !

**Comment by wankdanker** [comment]
For anyone who has a Windows build environment (possibly @orenz ), try installing with `npm install odbc`. Make sure that you have previously installed node-gyp globally with `npm install -g node-gyp`.

I haven't tested extensively yet and performance doesn't look great on my MSSQL server. 

If you find bugs or additional requests, please open a separate issue. As soon as I hear confirmation that this is working for others on Windows, I will be closing this issue.

Thanks everyone!

**Comment by orenz** [comment]
WORKS !!!

looks ok, however I will run some more tests.

Thanks ! This helps me very much.

**Comment by w1nk** [comment]
Dan,

Awesome job! I'll have a windows build env later today (new job) so I
should be able to lend you a hand if you need!

**Comment by merrittholmes** [comment]
Hi Guys,

IS there a windows version you can share? Or specific instructions for a newbie?

Cheers

Mike

**Comment by wankdanker** [comment]
Hey @merrittholmes,

I do not have a recent version of the windows version to share. The next time I build one, I will try to bundle it up and share a link here. I wouldn't count on this being any time soon, though.

Dan

**Comment by petermikitsh** [comment]
I installed Python 2.7 and Visual Studio Express 2013 for Desktop and was able to build on Windows 7 using node-gyp with no problem. I think the issue can be closed.

Pete

**Comment by wankdanker** [comment]
Thanks, Pete. Yeah, this is fixed.

As long as you have Python 2.7 and Visual Studio Express installed you can install node-odbc with:

```
C:\project> npm install odbc
```
