### ISSUE TITLE
node-odbc and DB2

### ISSUE THREAD

**Issue by praveend** [w1nk/node-odbc#26]
Hi,

I am interested in using node-odbc with DB2. To start with I would like to run the node-odbc test-suite against DB2. Could you let me know how to run the tests.

Also is there any API doc that I can refer to for knowing the different APIs exposed by node-odbc and their functionality

Thanks in Advance

Praveen

**Comment by praveend** [comment]
Hey,

Can you help me using node-odbc with DB2?

As progress from my side. I am able to set up node.js and node-odbc along with DB2 successfully.

Now it will be very useful if you could point me to API docs and how to run the test suite.

Thanks

Praveen

**Comment by wankdanker** [comment]
Hey @praveend,

The test suite isn't really a test suite at this point in time. It is just a bunch of individual tests without any glue to run them all. And the tests are certainly not all inclusive. If you want to experiment with them, you can change the connection string in test/common.js to match what your DB2 connection string would be. Then run individual tests with `node test-name.js`. I would review what the test does in code before executing them, though. Some of them create and remove tables, etc. I have not heard from any other users regarding these tests. So, as far as I am aware, I am the only person on Earth who has run them...

There are really no API docs. The README.md file contains the two most used methods of the API. `db.open(connectionString, callback)` and `db.query(sqlString[, bindingParameters], callback)`.

This is not a wrapper to all of the ODBC functionality.

Hope this helps.

Dan

**Comment by wankdanker** [comment]
Also, @praveend, if you have specific questions or need help in real time, I am in #node.js on freenode IRC as wankdanker.

**Comment by wankdanker** [comment]
I have updated the README to have a more explicit API section. Check it out here:

https://github.com/wankdanker/node-odbc/blob/master/README.md

I am going to close this issue now because the API docs have been updated and the test suite completion is a different issue. If you have specific issues with getting DB2 to work then by all means open another issue.

Thanks.

**Comment by praveend** [comment]
Hey, @wankdanker , Thanks for the reply will get some hands on by running some tests as mentioned. Also thanks for the README update.

Will get in touch with you for further help or issues via irc or this forum.

Thanks

Praveen
