### ISSUE TITLE
Previous column value fetched for a column when its actual value is NULL

### ISSUE THREAD

**Issue by praveend** [w1nk/node-odbc#29]
Hi,

I am using DB2 with node-odbc and found this bug where previous value is being fetched for a column if it's actual value is null in the database.

Steps to repro the issue

```
    a) create a table "create table foo (id integer, col1 varchar(10))"

     b) insert 2 rows as below

             insert into foo (id) values (1)
             insert into foo (id, col1) values (2, 'praveen')

     c) run the test sql-cli.js and issue the below select statement

             select * from foo

     you will see a result set as below

             [ { ID: 1, COL1: '1' }, { ID: 2, COL1: 'praveen' } ]
```

as you can see COL1 of the first row has a value '1' which actually had to be NULL.

Thanks

Praveen

**Comment by wankdanker** [comment]
In case anyone is interested in this issue, @praveend and I have discussed this and it seems to be that the DB2 ODBC driver implements the `SQLGetData()` function as the following:

``` C
SQLRETURN   SQLGetData  (
                SQLHSTMT          StatementHandle,     /* hstmt */
                SQLUSMALLINT      ColumnNumber,        /* icol */
                SQLSMALLINT       TargetType,          /* fCType */
                SQLPOINTER        TargetValuePtr,      /* rgbValue */
                SQLINTEGER        BufferLength,        /* cbValueMax */
                SQLINTEGER        *StrLen_or_IndPtr);  /* pcbValue */ 
```

Whereas sql.h declares `SQLGetData()` as:

``` C
SQLRETURN   SQLGetData  (
                SQLHSTMT        StatementHandle,
                SQLUSMALLINT    ColumnNumber, 
                SQLSMALLINT     TargetType,
                SQLPOINTER      TargetValue,
                SQLLEN          BufferLength,
                SQLLEN          *StrLen_or_Ind);
```

SQLLEN is defined as a `long` in the DB2 driver and as an `int` in unixODBC. This is causing some a strange issue when comparing the length of the returned value.

**Comment by praveend** [comment]
Hi @wankdanker 

The SQLGetData function definition is not the problem. DB2 ODBC has the definition as per ODBC spec itself, there is no difference in that. http://publib.boulder.ibm.com/infocenter/db2luw/v9r7/topic/com.ibm.db2.luw.apdv.cli.doc/doc/r0000604.html

The interesting thing is the behaviour during comparison, which I am not able to reason out yet. When the value of len is printed I see a -1 but somehow the comparison fails. Could anyone explain what could be the problem.

**Comment by wankdanker** [comment]
@praveend, My bad. I was looking at an old document for DB2 (http://publib.boulder.ibm.com/infocenter/db2luw/v8/index.jsp?topic=/com.ibm.db2.udb.doc/ad/r0000604.htm), which is unforunately, DB2's first Google result for SQLGetData.

I wonder if this has anything to do with 64 bit driver support (http://www.unixodbc.org/doc/ODBC64.html). I wonder if somehow the len parameter is getting written to as a 32 bit integer but when the comparison is happening it is tested as a 64 bit integer. So, the first 32 bits may have the correct value of -1, but the second 32 bits has bogus data in it. Combined together they might equal some value other than -1.

So, when you cast len to a SQLINTEGER (a 32 bit integer) during the check it may only be comparing the first 32 bits which was properly set and is thus -1.

I'm not sure if that is even possible; this is pure conjecture. :)

**Comment by praveend** [comment]
Hi @wankdanker,

The issue was related to the 64-bit support. DB2 provides 64-bit version of library that needs to be used when using unixODBC. I was linking to a wrong library (the one with SQLLEN defined as 4 bytes) and hence the problem. After linking to the right library the program works fine.

Will try other use cases with the new library and check how it goes with node-odbc and DB2 combination.

Thanks for your support Daniel

Regards

Praveen

**Comment by wankdanker** [comment]
Cool. Glad to hear you got it worked out. :)
