### ISSUE TITLE
Encoding problem (MSSQL)

### ISSUE THREAD

**Issue by wirrareka** [w1nk/node-odbc#3]
I tried using node-odbc to connect to our Microsoft SQL Server 2005, 
After running a query i get this warning for each row:

EIO_Query => [FreeTDS][SQL Server]Some character(s) could not be converted into client's character set.  Unconverted bytes were changed to question marks ('?')

I wouldn't bother about the warnings but also all the local characters are replaced for � in result data.

My FreeTDS is configured properly with client charset set as UTF-8.
I've got no issues connecting to our mssql server with freetds under my ruby and python apps.

Am I doing something wrong or is it a bug ? 

Matej Drzik

**Comment by w1nk** [comment]
It probably is a localization bug.  I'll look into it and let you know, thanks for the report.

**Comment by wankdanker** [comment]
Wirrareka, 

I received this warning before and I believe that I fixed it by making sure that TDS_Version = 8.0 was set in the connection string or in the DSN configuration of odbc.ini. I also set "tds version = 8.0" in the global section of freetds.conf

Let me know if that helps. 

Thanks,

Dan

**Comment by wankdanker** [comment]
Sorry, that's not correct. The TDS_Version is used to fix the maximum 30 character column name issue. I have fixed this before though and it is working in my setup, so let me see if I can figure out what I did.

**Comment by wankdanker** [comment]
Here is something interesting... When I connect with a connection string like:

"DRIVER={FreeTDS};SERVER=server;UID=user;PWD=password;DATABASE=database;TDS_Version=8.0;"

I do receive the warnings. But if I use a connection string like:

"DSN=myMssqlDsn;UID=user;PWD=password;DATABASE=database;"

with odbc.ini:

```
    [myMssqlDsn]
    Driver          = FreeTDS
    Description     = My Serve Description
    Trace           = No
    Servername      = server
    Database        = database
    TDS_Version     = 8.0
```

and freetds.conf

```
    [global]
            tds version = 8.0
            client charset = UTF-8

            # If you get out-of-memory errors, it may mean that your client
            # is trying to allocate a huge buffer for a TEXT field.  
            # Try setting 'text size' to a more reasonable limit 
            text size = 4294967295

    # This is our primary SQL Server
    [server]
            host = server
            port = 1433
```

I do not receive the warnings and I do receive all characters in my result sets. I'm not sure what exactly is going on here but my guess is that the freetds.conf settings are only applied when using an odbc.ini DSN. So there must be a way to set the client charset from the connection string, but I have not been able to find that yet.

Are you currently connecting with a DSN?

Hope this helps,

Dan

**Comment by wankdanker** [comment]
I can't find a way to specify the client charset from the connection string. From FreeTDS's (freetds-0.82) connectparmas.c it looks like the following connection string options are handled by the odbc_parse_connect_string function:

```
SERVER
SERVERNAME
DSN
DATABASE
UID
PWD
APP
WSID
LANGUAGE
Port
TDS_Version
TextSize
PacketSize
```

**Comment by wirrareka** [comment]
Thanks for your replies, i found the mistake, it's probably not related to node-odbc, but it was a very weird one. I'm on Mac/10.6, i installed unixodbc and freetds with homebrew installer (i needed unixodbc, not iodbc), having it installed under /usr/local/Cellar dir. I already tried connecting DSN and without DSN before, and it haven't changed the encoding. Also I made myself sure that it's reading the right odbc.ini  by moving it to other location, and it failed to connect which was correct for the test.
Nothing helped.. 
So i tried just to be sure to locate odbc.ini and found another one (old one) under /Library/ODBC/odbc.ini, which had the DSN aswell with server instead of servername (so it did not went through the freetds config at all, not even reading global config), it even had wrong driver (TDS instead of FreeTDS)..
Strangely I need both odbc.ini files to have it working.. 

So I guess that's probably a weird problem on my side with odbc build. I tried if my rails and python apps also require both files and they did, however both rails and python used/use the dsn specified in /usr/local/Cellar/unixodbc, while node-odbc uses the other one from /Library/ODBC. I don't really know why this exception happens, maybe something with environment, will try to play with it tommorow, i didn't made any specific environment setups for rails/sinatra and django )

Anyway, thank you very much for your time, my navision bridge is working now :)

**Comment by wankdanker** [comment]
Awesome! Glad to hear it! :)

**Comment by w1nk** [comment]
wirrareka, I can't seem to see your comment, judging from wankdanker's response though, it looks like you got it sorted out?  Let me know and I'll close this :).

**Comment by bbigras** [comment]
I have the same problem. Was @wirrareka able to specify the client charset from the connection string?

**Comment by wankdanker** [comment]
For the record, @wirrareka's response was:

> Thanks for your replies, i found the mistake, it's probably not related to node-odbc, but it was a very weird one. I'm on Mac/10.6, i installed unixodbc and freetds with homebrew installer (i needed unixodbc, not iodbc), having it installed under /usr/local/Cellar dir. I already tried connecting DSN and without DSN before, and it haven't changed the encoding. Also I made myself sure that it's reading the right odbc.ini  by moving it to other location, and it failed to connect which was correct for the test.
> 
> Nothing helped..
> 
> So i tried just to be sure to locate odbc.ini and found another one (old one) under /Library/ODBC/odbc.ini, which had the DSN aswell with server instead of servername (so it did not went through the freetds config at all, not even reading global config), it even had wrong driver (TDS instead of FreeTDS)..
> Strangely I need both odbc.ini files to have it working..
> 
> So I guess that's probably a weird problem on my side with odbc build. I tried if my rails and python apps also require both files and they did, however both rails and python used/use the dsn specified in /usr/local/Cellar/unixodbc, while node-odbc uses the other one from /Library/ODBC. I don't really know why this exception happens, maybe something with environment, will try to play with it tommorow, i didn't made any specific environment setups for rails/sinatra and django )
> 
> Anyway, thank you very much for your time, my navision bridge is working now :)

**Comment by wankdanker** [comment]
So, I just looked in to this again. On my system (Ubuntu Oneiric), if I `apt-get source freetds-bin` and look at `src/odbc/connectparams.c`, in the function `odbc_parse_connect_string`, there is no client charset option. However in newer versions of FreeTDS, they do parse this option (see [Line 375](http://freetds.cvs.sourceforge.net/viewvc/freetds/freetds/src/odbc/connectparams.c?revision=1.94&view=markup) on SourceForge). So I think the issue here may be the FreeTDS driver in your distribution. 

I believe that the charset option is parsed if it's specified in ODBC.ini.

**Comment by wankdanker** [comment]
FYI: there are bug reports at Ubuntu and Debian to get a newer FreeTDS package.

https://bugs.launchpad.net/ubuntu/+source/freetds/+bug/887374
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=642069
