### ISSUE TITLE
If list of parameters contains a null or (any non-string?) then all passed parameters will be null

### ISSUE THREAD

**Issue by yozik04** [w1nk/node-odbc#30]
This is my test case:

``` javascript
var common = require("./common")
        , odbc = require("../odbc.js")
        , db = new odbc.Database();


db.open(common.connectionString, function (err) {
        if (err) {
                console.error(err);
                return;
        }

        db.query("select ? as fish, ? as null_val"
                , ["fish", null]
                , function (err, data, more) {
                        if (err) {
                                console.error(err);
                                process.exit(1);
                        }

                        console.error(data);
                }
        );
});
```

Expected result:
[ { fish: "fish", null_val: null } ]

Actual result:
[ { fish: null, null_val: null } ]

I am trying this on OS X Lion 10.7.5 Using unixODBC + FreeTDS. Connecting to MS SQL Server.

Same thing happens if there will be a numeric value in parameters.

**Comment by wankdanker** [comment]
Hi @yozik04,

Thanks for the report. I have seen this too and did spend some time trying to fix it. But, I was unable to determine why this was happening. 

My v0.5 branch has failing tests for booleans, decimals and numbers (https://github.com/wankdanker/node-odbc/tree/v0.5/test). I will add a test for nulls and hopefully we'll get this figured out soon.

Thanks,

Dan

**Comment by yozik04** [comment]
Installed version from github
$ npm install https://github.com/wankdanker/node-odbc/archive/v0.5.tar.gz

Tried to run tests. Decimals and nulls does not work.

$ node run-tests.js

Warning : there are 1 disabled tests

Running test : test-closed ... success  
Running test : test-connection-object ... fail  
Running test : test-date ... success  
Running test : test-describe-column ... fail  
Running test : test-describe-database ... fail  
Running test : test-describe-table ... fail  
Running test : test-instantiate-one-and-end ... success  
Running test : test-memory-leaks-new-objects ... success  
Running test : test-multi-open-close ... fail  (Timed Out)
Running test : test-multi-open-query-close ... fail  (Timed Out)
Running test : test-open-close ... success  
Running test : test-open-dont-close ... fail  (Timed Out)
Running test : test-param-select-with-booleans-only ... success  
Running test : test-param-select-with-decimals-only ... fail  
Running test : test-param-select-with-nulls-mixed ... fail  
Running test : test-param-select-with-numbers-mixed ... success  
Running test : test-param-select-with-numbers-only ... success  
Running test : test-param-select-with-strings-only ... success  
Running test : test-pool-close ... fail  (Timed Out)
Running test : test-pool-connect ... fail  (Timed Out)
Running test : test-query-create-table ... success  
Running test : test-query-drop-table ... success  
Running test : test-query-insert ... fail  (Timed Out)
Running test : test-query-select-fetch ... success  
Running test : test-query-select-fetchAll ... success  
Running test : test-query-select-unicode ... fail  
Running test : test-query-select ... success  
Running test : test-require-and-end ... success

$ node test-param-select-with-nulls-mixed.js
assert.js:102
  throw new assert.AssertionError({
        ^
AssertionError: {"state":"S1004","error":"[node-odbc] SQL_ERROR","message":"[FreeTDS][SQL Server]Invalid data type","query":"select ? as TEXTCOL == null
    at /Users/user/node/node_modules/odbc/test/test-param-select-with-nulls-mixed.js:14:18
    at Database.close.self.queue.push.args (/Users/user/node/node_modules/odbc/odbc.js:186:26)

**Comment by wankdanker** [comment]
Thanks for the update, @yozik04.

These tests pass with the sqlite odbc driver. But, I also see it failing in this way with FreeTDS. Will see what I can do.

Thanks,

Dan

**Comment by yozik04** [comment]
Thank you for your great work :) I am happy to help to make it better

Jevgeni

26.11.2012, в 18:29, Dan VerWeire notifications@github.com написал(а):

Thanks for the update, @yozik04 https://github.com/yozik04.

These tests pass with the sqlite odbc driver. But, I also see it failing in
this way with FreeTDS. Will see what I can do.

Thanks,

Dan

—
Reply to this email directly or view it on
GitHubhttps://github.com/w1nk/node-odbc/issues/30#issuecomment-10722109.

**Comment by wankdanker** [comment]
As I mentioned in the latest commit, I believe I have fixed this issue for FreeTDS. The nulls were failing because SQL Server didn't know what to do with the SQL_UNKNOWN_TYPE type. So I just changed it to SQL_VARCHAR. I hope that works for other databases (It does work for sqlite). 

The issue with the decimal case was that the size and decimals were both set to zero. Setting them to something other than zero allows the test to pass, but will likely work incorrectly if a value is passed that requires more precision.

So, we need to figure out the best way to determine the integer length and decimal length so that we can set those values properly on the Parameter struct. Once that is done and working, I might actually consider this issue closed. :)

**Comment by yozik04** [comment]
Great. Looks like this fixed the issue. Thank you. =)
Tests do pass.

About integer and decimal length. I think something interesting can be found here:
https://github.com/WindowsAzure/node-sqlserver/blob/master/src/OdbcConnection.cpp#L273

**Comment by wankdanker** [comment]
Also here: https://github.com/WindowsAzure/node-sqlserver/blob/master/src/OdbcOperation.cpp#L171

**Comment by wankdanker** [comment]
I have committed changes which should set proper values for the parameter. They are no longer guesses. :)

**Comment by yozik04** [comment]
Perfect, thanks! =)
