### ISSUE TITLE
v0.4.4 requests libodbc.so.1

### ISSUE THREAD

**Issue by clncln1** [w1nk/node-odbc#36]
Having updated from node 0.8 + odbc 0.4.3 to node 0.10 and odbc 0.4.4 seems to have broken something. The module tries to fetch libodbc.so.1 which the previous version didn't try.

**Comment by wankdanker** [comment]
Weird, I responded to this yesterday, but I must not have actually submitted it! Here is what changed from 0.4.3 to 0.4.4: https://github.com/wankdanker/node-odbc/compare/v0.4.3...v0.4.4

My installation on Ubuntu 12.04.2, node v0.10.2, node-gyp v0.9.5 works properly. Below is my `ldd` for `odbc_bindings.node`. It loads libodbc.so.1 and like I said everything is working properly for me. Is this causing it to crash on you?

``` bash
$ ldd odbc_bindings.node 
        linux-vdso.so.1 =>  (0x00007fff0cf45000)
        libodbc.so.1 => /usr/lib/x86_64-linux-gnu/libodbc.so.1 (0x00007f157b85b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f157b55b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f157b19b000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f157af91000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f157ad74000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f157aa77000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f157bcfe000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f157a861000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f157a65d000)
```

**Comment by wankdanker** [comment]
Haven't heard back about this. I tested 0.4.4 on a box running node 0.8 and it was loading libodbc.so.1. If this is still causing an issue for you we can re-open this issue..
