### ISSUE TITLE
Connection Issue - RESOLVED

### ISSUE THREAD

**Issue by srhart** [w1nk/node-odbc#37]
Hi,

I have been trying a couple of connections through FreeTDS to MS SQL. I have one working that has an allocated port SERVER=xx.xx.xx.xx\\instance (note the double \\): The issue I am having is with a standard connection on port 1433. SERVER=xx.xx.xx.xx but not sure if I should be passing the port on the db.open. The ocbc(inst).ini is configured correctly as I can get access through isql. 

UPDATE *\* I seem to have got it working, added PORT=1433 into the cn.

I can write a wiki if anyone likes?

**Comment by wankdanker** [comment]
Awesome. Have at it. :)
