### ISSUE TITLE
latest 5.14 level more asynchronous? (probably not an issue but wanted to update you)

### ISSUE THREAD

**Issue by amcintyre99** [w1nk/node-odbc#39]
I would have emailed this but I don't have any address for you.

Thanks for all the work on issue #32 by the way!!! it's working great....

Interesting thing... I was running through last Friday afternoon with your 5.10 level (with your May 3 changes) and no issues. Then I upgraded to your 5.14 Friday evening, tested and again no issues.

Then under a heavier than normal load on Monday and today, an area of my code I thought was ok (stringing together partial http responses until I get a complete well formed xml packet) started throwing errors saying malformed xml. Sure enough, it was obvious I was overlaying the string. Not many, out of 3mill maybe about 3k so 0.1% but still...

No problem and I bet it's my bad related to piecing together http... and I've read I should be using mikeal's request module instead of core http client anyway... so I've started converting and hope this issue will go away.

But my question (finally got here) was what might have changed between May 3 and May 10 in your code that could have made the database calls work differently under heavy load?

had switched to node 10.5 back on May 3 and nothing else changed over the weekend...

Thanks again!!

**Comment by wankdanker** [comment]
Awesome. I'm glad to hear that things are working well for you. Here are the changes from [v0.5.10 to v0.5.14](https://github.com/wankdanker/node-odbc/compare/v0.5.10...v0.5.14).

Mainly what changed was eliminating deprecated calls to ODBC 2.0 functions. So, we are now only using ODBC 3.x functions. My hope was to improve the potential for dynodbc to work.

There are a couple places where I added some return value checking and properly returning errors if there were any. These checks were mainly to ensure that a handle was properly allocated.

The error processing no longer uses SQLError as that was a ODBC 2.0 function and we now use SQLGetDiagRec which requires a loop to gather the error information. So, if your system is getting errors, it may take a minuscule amount more CPU to get the error data.

I don't know though these changes seems like they would be really marginal. You could try installing one version at a time and see where it breaks...

``` bash
npm install git://github.com/wankdanker/node-odbc.git#v0.5.11
npm install git://github.com/wankdanker/node-odbc.git#v0.5.12
npm install git://github.com/wankdanker/node-odbc.git#v0.5.13
npm install git://github.com/wankdanker/node-odbc.git#v0.5.14
```

Wish I had a better idea for you. :-\

**Comment by wankdanker** [comment]
Wait, were you saying that things are working better with the latest version?

**Comment by amcintyre99** [comment]
"minuscule amount more CPU to get the error data."... on the 5 or so out of 25 nodes that were consistently getting the xmlparse error from db2, yes, they had much higher cpu...

but on the other 20? they were actually lower cpu on higher volume... so yes, I think things are working better... especially if the request module fixes all my http packet issues... that I thought were gone...

volume handled today was highest ever... 4.7m INSERTs in 6.5 hour period...

my suspicion is that things are also better in the async area... which uncovered my issue... maybe because of odbc 3.0? i searched around but could find nothing on it being better in db2 land...

**Comment by wankdanker** [comment]
Yeah, my guess is that it would be the ODBC 3.0 stuff. When using ODBC 2.0 functions, the ODBC driver manager would map 2.x function calls to the proper 3.x function call. That probably had some overhead. And yeah, maybe there is some other goodness that we get for free by declaring that we are using ODBC 3.0. 

I'm glad to hear that it sounds like things are working out better for you.

**Comment by amcintyre99** [comment]
After two weeks (10 market days) on your 5.14 level, everything is working great.

Especially yesterday where I went from my usual 5m inserts in 6.5 hours to about 25m with no problems.

You can close this one out and thanks again!!

**Comment by wankdanker** [comment]
Awesome. That's great to hear. Thank you for the feedback. :)
