### ISSUE TITLE
cannot install on ubuntu

### ISSUE THREAD

**Issue by viniciusgati** [w1nk/node-odbc#40]
i installed node version 0.8.24 and im having problems installing the package

gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.0
gyp info using node@0.8.24 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vinicius/node-odbc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vinicius/.node-gyp/0.8.24/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/vinicius/.node-gyp/0.8.24',
gyp info spawn args   '-Dmodule_root_dir=/home/vinicius/node-odbc',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/vinicius/node-odbc/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
In file included from ../src/odbc.cpp:25:0:
../src/odbc.h:28:17: fatal error: sql.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
make: Leaving directory`/home/vinicius/node-odbc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:680:10)
gyp ERR! System Linux 3.5.0-17-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/vinicius/node-odbc
gyp ERR! node -v v0.8.24
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok

**Comment by wankdanker** [comment]
Hey @viniciusgati,

Did you install all the requirements? (https://github.com/wankdanker/node-odbc#requirements)

Dan

**Comment by viniciusgati** [comment]
Tanks now its working :+1:
