### ISSUE TITLE
The callback for db.close() never gets invoked

### ISSUE THREAD

**Issue by theduderog** [w1nk/node-odbc#41]
Sorry, this may be more of a question than an issue but I don't know where else to ask it.

If I call open() on the db object, then close(), the callback for close() will get invoked.  If, however, I add in a call to db.describe(), the callback for close() never gets invoked.  Is there some kind of cleanup I need to do?

https://gist.github.com/theduderog/d24bf6820d9a034f1763

I'm using Ubuntu 12.04,  node v0.10.11, libsqliteodbc 0.91-3, unixodbc 2.2.14p2-5ubuntu3 but I've also tested that the same behavior happens with the SAP Hana odbc driver.

**Comment by theduderog** [comment]
I've tested the db.query() function and it does not have the same issue.

**Comment by wankdanker** [comment]
What version of node-odbc? Maybe try with `npm install git://github.com/wankdanker/node-odbc.git#v0.5`

**Comment by theduderog** [comment]
I was using 0.4.4.  Installing 0.5 as you suggested has fixed the problem.
 Thanks!

**Comment by wankdanker** [comment]
Cool. Glad that worked. I'll get that version published on npm as soon as I guarantee there are no memory leaks.
