### ISSUE TITLE
Returning only 20653 rows

### ISSUE THREAD

**Issue by disordinary** [w1nk/node-odbc#42]
The same query run with isql or on the server returns 30500 rows.

moreResultSets is false.

**Comment by wankdanker** [comment]
What version of node-odbc?

**Comment by disordinary** [comment]
0.4.4

**Comment by wankdanker** [comment]
Try with `npm install git://github.com/wankdanker/node-odbc.git#v0.5`.

I've been waiting to push that out till I prove to myself that there are no memory leaks, but I may have to just do it because there are tons of new features and seems like bug fixes.

**Comment by wankdanker** [comment]
I was able to select some 45k rows with v0.5.14 and that exactly matched what I queried in MSSQL management studio.

**Comment by disordinary** [comment]
That worked perfectly, thanks for the quick reply.

**Comment by wankdanker** [comment]
Awesome. Glad to hear it. You are welcome.
