### ISSUE TITLE
Can't insert a text string with size > 8000 bytes

### ISSUE THREAD

**Issue by jcamus** [w1nk/node-odbc#48]
When trying to insert with node.js 0.8.25 and node_odbc version 0.4.4 a string with size > 8000 bytes. It fails with the following error message :

[node-odbc] SQL_ERROR","message":"[Microsoft][SQL Server Native Client 11.0]String data, right truncation

If string is 8000 bytes length or lower it works fine.

If I insert the string directly with a database editor it works. So database and table have correct colunm types (varchar(max))

In database.cpp (line 678) code is :  
params[i].type = SQL_VARCHAR

is SQL_LONGVARCHAR better to manage big strings ?

Please help !

**Comment by wankdanker** [comment]
Try installing with:

`npm install https://github.com/wankdanker/node-odbc.git#v0.5`

Should be version v0.5.21. 

Will investigate SQL_LONGVARCHAR and make a new release if v0.5.21 doesn't work for you.

**Comment by wankdanker** [comment]
Just tried out a simple test on v0.5.21 and it failed. Will work on this.

**Comment by jcamus** [comment]
Ok thanks. By the way I tried to change params[i].type = SQL_LONGVARCHAR and recompiled with node-gyp. 
when running a request I had a SQLSERVER error :
{"state":"37000","error":"[node-odbc] SQL_ERROR","message":"[Microsoft][SQL Server Native Client 11.0][SQL Server]Statement(s) could not be prepared

**Comment by jcamus** [comment]
I want to add that the SQL_SERVER table containing the big string is type :
VARCHAR(max) so no problem when inserting via standard SQL and database editor tool to insert a string containing more than 8,000 bytes.

**Comment by wankdanker** [comment]
Hey @jcamus,

If you try installing with `npm install https://github.com/wankdanker/node-odbc.git#v0.5` you might have better luck now. I think I got it fixed and have released v0.5.23 on my fork.

This version also has fixes which will retrieve really long values from the database. Previously it was limited to ~1MB or whatever the default buffer size is.

If you were trying to set `params[i].type = SQL_LONGVARCHAR` on v0.5.21, you may have received that error because UNICODE was enabled and it should have been SQL_WLONGVARCHAR. That's all just a guess though.

Let me know how things go.

Thanks,

Dan

**Comment by jcamus** [comment]
Sorry, but when trying to install the 0.5 version I have the following error message :

npm http 200 https://github.com/wankdanker/node-odbc.git#v0.5
npm ERR! not a package /home/jcamus/tmp/npm-29483/1374246832346-0.08589721564203501/tmp.tgz
npm ERR! Error: ENOENT, open '/home/jcamus/tmp/npm-29483/1374246832346-0.08589721564203501/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.2.0-48-generic
npm ERR! command "/home/jcamus/nodeJs/bin/node" "/home/jcamus/nodeJs/bin/npm" "install"
npm ERR! cwd /home/jcamus/myApp/node_modules/common-db
npm ERR! node -v v0.8.23
npm ERR! npm -v 1.2.18
npm ERR! path /home/jcamus/tmp/npm-29483/1374246832346-0.08589721564203501/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34

**Comment by wankdanker** [comment]
Sorry about that. It should actually be `npm install git://github.com/wankdanker/node-odbc.git#v0.5`.

I forgot that http[s]:// only works for archives, not repositories. :-\

**Comment by wankdanker** [comment]
Any luck with this, @jcamus?

**Comment by gintonic25** [comment]
Hi @wankdanker . @jcamus  is on holiday :)

Sorry, I tried your fix and ran accross another error when trying to insert my data : {"error":"[node-odbc] SQL_ERROR","message":"[Microsoft][SQL Server Native Client 11.0][SQL Server]Statement(s) could not be prepared.","state":"42000"}

I found a workaround for the node-odbc version 0.4.4 i'm using. I noticed that the "String data, right truncation" occurs when I use the node-odbc api with params : db.query(query, params, callback) where the params array contains my big JSON object.
However, if I fill manually the query with my data and send an empty array : db.query(query, [], callback), the data is inserted in my nvarchar(max) typed column.

Regards

**Comment by wankdanker** [comment]
Hi @gintonic25. Lucky @jcamus  :)

If you would like to try v0.5.25 you might have better luck as it includes this patch: https://github.com/wankdanker/node-odbc/commit/3bc0625635befb3f94fd611e24f176da7131b8f6.

I was seeing that same error as you and this seemed to fix it.

Would be curious if it works for you too.

Thanks,

Dan

**Comment by gintonic25** [comment]
Hi @wankdanker 

Thanks for the fix !
Good news : I tried the v0.5.25 and my data is inserted in the table.
Bad news : my driver is unstable now. My application crashes after each database access with the following error :

```
  cb(err);   TypeError: undefined is not a function    at Database.close (/home/XXX/XXX/node_modules/odbc/lib/odbc.js:137:7)     Process finished with exit code 1
```

I guess this is a compatibility break with the version v0.5.xx, but i don't have a hint.

Thanks

**Comment by wankdanker** [comment]
Without looking at the code it looks like you are calling the `close()` method without passing a callback. I'll make sure that possibility is handled so that it doesn't blowing things up for people.

Thanks for the feedback.

**Comment by jcamus** [comment]
Hello I am back to this issue still not resolved.
I have many questions.

1) why the version 0.5.26 (seems latest avaiable) when having in my package.json : odbc : *
But this version is never visibled into the main page of https://github.com/w1nk/node-odbc/ ??

2) I still have the problem when inserting data as prepared request, SQL Server reject the insertion with a message :
(odbcImpl.js) ERROR DATABASE : {"error":"[node-odbc] SQL_ERROR","message":"[Microsoft][SQL Server Native Client 11.0]Invalid precision value","state":"HY104"}
My string is UTF-8 and length is > 4000. 

Please help! ;-)

**Comment by wankdanker** [comment]
Hey @jcamus,

1) I'm going to start publishing to npm more often. I am also changing the repo in package.json to my repo since I have been doing most of the updates lately. Hopefully that will help avoid confusion as the original author has been busy with other stuff for some time.

2) Could you provide some test code that reproduces this issue? That would be most helpful.

**Comment by wankdanker** [comment]
If this is not working yet, please open another issue.

Thanks.
