### ISSUE TITLE
Truncated error message

### ISSUE THREAD

**Issue by madelynnblue** [w1nk/node-odbc#51]
Using 0.5.25 from git, mac osx, node 0.10.17, an error occurs on `db.open`, but both the state and message are truncated:

`{ error: '[node-odbc] SQL_ERROR', message: '[', state: 'I' }`

Any ideas?

**Comment by wankdanker** [comment]
Any time I have seen any sort of string truncation where only the first character is left it has been some Unicode issue. What database are you using this with?

You can try without Unicode by removing the 'UNICODE' flag from `binding.gyp` and then rebuilding with `node-gyp rebuild`.

**Comment by madelynnblue** [comment]
Yes, that fixed the error message display. Now to fix the error...

For reference, I think the database at this point is irrelevant, because the error message is:

`message: '[iODBC][Driver Manager]Specified driver could not be loaded',
  state: 'IM003'`

**Comment by wankdanker** [comment]
Agreed. I wonder if there is something up with the osx UnixODBC. This does not happen on Ubuntu 13.04 with UnixODBC 2.2.14.

**Comment by madelynnblue** [comment]
For the archives: on OSX, you need not install unixodbc, since iodbc is included by default.

If using FreeTDS (which can be installed via `brew install freetds`), the 'driver' section of the connection string should be the location of the .so: `/usr/local/lib/libtdsodbc.so`, WITHOUT enclosing { and }.
