### ISSUE TITLE
unixodbc not used on mac osx

### ISSUE THREAD

**Issue by madelynnblue** [w1nk/node-odbc#52]
iODBC is included by default on osx. After installing unixodbc with `brew install unixodbc`, and freetds with `brew install freetds --with-unixodbc`, node-odbc still uses iODBC. This seems to be because it adds a `-lodbc` build flag, which then uses `/usr/lib/libodbc.a`.

I symlinked the libodbc.dylib file from the unixodbc install directory as libunixodbc.dylib, and changed the build flag to `-lunixodbc` and rebuilt. This caused node-odbc to use the unixodbc driver, as desired.

I'm not sure what a correct fix for this would be, but wanted to document it for anyone else who came by since it's quite complicated.

(The motivation for this was that iODBC appears to have some problems with unicode. It was working fine for most queries, until I had some strange characters in a string, after which it silently failed and sent an empty string.)

**Comment by wankdanker** [comment]
I wonder if there is a way to add a path to `binding.gyp` that would check wherever `brew install unixodbc` installs to before checking the default `/usr/lib/libodbc.a`. I do not know how build systems/compilers/linkers resolve where a linked library resides. So, if anyone has any input on that, please help..

**Comment by w1nk** [comment]
I just ran into this yesterday as well.  I was able to fix it by modifying the binding.gyp and adding the -L (search path) so that it finds unixodbc before it finds iodbc:

```
                            [ 'OS == "mac"', {
                                    'libraries' : [ 
                                    '-L/usr/local/lib',
                                            '-lodbc' 
                                    ]
                            }]
```

Should we just assume that as a default on macs to avoid this?  iODBC is nasty with this binding (lots of things half work and frustrate).

**Comment by madelynnblue** [comment]
That makes the most sense to me. Even when successfully built against iODBC, nothing else worked, so it was useless.

**Comment by wankdanker** [comment]
Awesome. `'-L/usr/local/lib'` is exactly what I was looking for. I'll add it to the default binding.gyp.

**Comment by wankdanker** [comment]
Assuming this is fixed.
