### ISSUE TITLE
odbc_bindings.node: undefined symbol: SQLGetDiagField

### ISSUE THREAD

**Issue by amcintyre99** [w1nk/node-odbc#53]
Still trying to get prepare or prepareSync to return an error on bad sql but can't get around the above msg...

Your test also fails:

$ node test-prepare.js 
node: symbol lookup error: 
......../node_modules/odbc/build/Release/odbc_bindings.node: undefined symbol: SQLGetDiagField

It might be related to this:
https://github.com/wankdanker/node-odbc/commit/4d5e700d0042eb256477a6bf7b69cdb32134d88d

thanks!!

**Comment by amcintyre99** [comment]
and i'm at node 10.18 odbc 5.26 with dynodbc and without unicode (i can only get one or the other to npm update without errors, not both - may not be placing them both in binding.gyp correctly)

**Comment by amcintyre99** [comment]
dynodbc is the issue, not only with prepare but executeNonQuery

with it off, i'm still not seeing any sql errs from prepare, which may or may not be an issue, but i am getting them again from executeNonQuery like i use to, which is fine because now i can debug my sql

so running without dynodbc for now

**Comment by wankdanker** [comment]
The only thing I can think of is that the driver your are using directly does not export SQLGetDiagField. Try running `nm -D /path/to/driver` to get a list of the exported functions. For example: `nm -D /usr/lib/odbc/libsqlite3odbc.so`. 

Maybe it only exports the W or A version of the function....

**Comment by amcintyre99** [comment]
I think it supports it. See below.

I'm not a cpp guy but doesn't this issue have something to do with your dynodbc.cpp and/or dynodbc.h missing SQLGetDiagField?

$ nm -D /home/db2inst1/sqllib/lib64/libdb2o.so |grep SQLGetDiagField
0000000000607d60 T SQLGetDiagField
00000000006d1a70 T SQLGetDiagFieldW
0000000000611840 T _Z16SQLGetDiagField2P19CLI_ERRORHEADERINFOP17CLI_STATEMENTINFOisPvsPsPhhhS4_

**Comment by wankdanker** [comment]
You are right! I just pushed some changes out that may work for this situation. I have only tested as far as making it compile. I am not sure if it works correctly. If you want to try it out (with or without UNICODE enabled) please do and let me know how it goes.

**Comment by paulhendrix** [comment]
I think that dynodbc.cpp and dynodbc.h doesn't include definition of this function.
You could add this by analogy to function for example SQLGetDiagRec.
http://msdn.microsoft.com/en-us/library/ms716256%28v=vs.85%29.aspx
http://msdn.microsoft.com/en-us/library/ms710181%28v=vs.85%29.aspx

**Comment by wankdanker** [comment]
@paulhendrix, This is what I attempted to do with: https://github.com/wankdanker/node-odbc/commit/7b9e8d553c53ff9fdd744a2a67fc2327032594e7

**Comment by amcintyre99** [comment]
yep, that fixed it - thanks!! now i can see any sql errors in dynodbc mode...

$ node test-prepare.js
assert.js:3488: Uncaught AssertionError: {"error":"[node-odbc] SQL_ERROR","message":"[IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token \"END-OF-STATEMENT\" == null

any idea how i can specify both dynodbc and unicode in binding.gyp? although db2 defaults to unicode so does it matter? and my code doesn't need i18n'ed anyway... i'm only caring to see if i can save some cpu%

saw these msgs during npm rebuild if it matters - and thx again!!

  CXX(target) Release/obj.target/odbc_bindings/src/dynodbc.o
../src/dynodbc.cpp: In function ‘int DynLoadODBC(char_)’:
../src/dynodbc.cpp:129:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:130:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:156:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:157:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:158:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:159:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:160:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:161:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:162:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:164:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:165:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:166:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:167:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:168:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:169:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:170:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:171:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:172:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:173:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:175:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:176:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:177:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:179:7: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../src/dynodbc.cpp:180:7: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]

**Comment by amcintyre99** [comment]
something i uncovered during this issue:

with purposely bad sql,
when using prepareSync, no err is thrown from prepare and then later with executeNonQuery, no err is thrown - this is not good

but,
with same purposely bad sql,
when using prepare with cb, no err is thrown from prepare and then later with executeNonQuery, err IS thrown - this is good

not sure if this was due to my lack of js skills but i just verified this again

db2 doing prepare not throwing err on bad sql may be normal, don't know

but prepareSync preventing executeNonQuery from returning err might be your issue

so I've switched to prepare with cb

and never thought i'd be happy to see sql errors :-)

**Comment by wankdanker** [comment]
Cool, thank you for the information about prepareSync/executeNonQuery not returning error messages on bad SQL. I'll look into that.

From what I have seen, it seems as if `SQLPrepare` does not actually evaluate the SQL statement for errors. I noticed this before and thought it was odd. The errors would ultimately come when you execute in some way or another. I'll look into this again though.

To enable UNICODE and dynodbc, your binding.gyp should look something like (note the defines section):

``` javascript
{
  'targets' : [
    {
      'target_name' : 'odbc_bindings',
      'sources' : [
        'src/odbc.cpp',
        'src/odbc_connection.cpp',
        'src/odbc_statement.cpp',
        'src/odbc_result.cpp',
        'src/dynodbc.cpp'
      ],
      'defines' : [
        'UNICODE',
        'dynodbc'
      ],
      'conditions' : [
        [ 'OS == "linux"', {
          'libraries' : [
            '-lodbc'
          ],
          'cflags' : [
            '-g'
          ]
        }],
        [ 'OS == "mac"', {
          'libraries' : [
            '-lodbc'
          ]
        }],
        [ 'OS=="win"', {
          'sources' : [
            'src/strptime.c',
            'src/odbc.cpp'
          ],
          'libraries' : [
            '-lodbccp32.lib'
          ]
        }]
      ]
    }
  ]
}
```

**Comment by amcintyre99** [comment]
Re prepareSync/executeNonQuery... when the SQL was good, it worked fine - weird

and I tried that exact coding in binding.gyp (minus the linux -lodbc parm) but "npm rebuild odbc" failed with lots of errors - i will try again after market close

**Comment by wankdanker** [comment]
I added a test case for how I interpreted your reported prepareSync/executeNonQuery issue. It's linked above, check it out and see if that looks like it should break. It doesn't break for me. `executeNonQuery` has an error'

**Comment by amcintyre99** [comment]
i get no return at all - so it wasn't my js skills :-)

$ node test-prepareSync-bad-sql.js
$

**Comment by wankdanker** [comment]
Unless I wrote the test wrong, it shouldn't display anything unless it does
not get an error from `execute` or `executeNonQuery`.

If it didn't fail on you, then an error was emitted from both `execute` and
`executeNonQuery` because of the bad SQL passed to `prepare`. Which I
believe should be the correct behavior assuming that `prepare` (and
internally `SQLPrepare`) does not actually evaluate the SQL statement for
correctness.

So, it seems like errors are passed along by both `execute` and
`executeNonQuery` if there is bad SQL. Which does not jive with the
behavior you saw earlier where `executeNonQuery` was not reporting errors.

Right?

**Comment by amcintyre99** [comment]
ok, sorry, i was getting it backwards

but... my code had the prepareSync (and now has the prepare with cb) followed by invoking a function, which invokes itself recursively always passing that original stmt from the prepare (see my earlier code in that original issue - plus i think you created some test code like that somewhere but i forget which one, sorry)

**Comment by amcintyre99** [comment]
remember this prepareSync issue was dynodbc related - so maybe the fix for SQLGetDiagField fixed it

or maybe i was confusing the issues (probably)

but i'm sticking with prepare with cb instead of prepareSync

**Comment by amcintyre99** [comment]
npm rebuild with dynodbc and unicode works, i think, with lots of msgs like below instead of what i was getting before

but when i run with it i get this (hope what looks like chinese copies in)
0 { error: '[node-odbc] SQL_ERROR',
  message: '䥛䵂孝䱃⁉牄癩牥⁝兓ㅌ㈰临†⁁慤慴慢敳挠湯敮瑣潩⁮潤獥渠瑯攠楸瑳‮匠䱑呓呁㵅㠰〰ਲ਼',
  state: '㠰〰1' }

i think i'm going back to just dynodbc :-)

from npm rebuild...................................
In file included from ../src/odbc.h:27:0,
                 from ../src/odbc.cpp:25:
../src/dynodbc.h:352:0: warning: "SQLSetConnectOption" redefined [enabled by default]
/usr/include/sqlucode.h:760:0: note: this is the location of the previous definition
../src/dynodbc.h:355:0: warning: "SQLError" redefined [enabled by default]
/usr/include/sqlucode.h:742:0: note: this is the location of the previous definition

**Comment by wankdanker** [comment]
Hahahaha. Unicode. smh.

I noticed all those warnings when I compiled with UNICODE and dynodbc. Not sure how to get rid of them or if it is even possible. 

Not sure I'll be able to solve that error message problem any time soon. I don't use dynodbc so it's on the edge of my support. If I do start using it, then I will definitely debug that.

**Comment by amcintyre99** [comment]
hey i'm happy with dynodbc by itself and prepare with cb so you can close this anytime

and thanks!!!!!!!!!!!!

**Comment by wankdanker** [comment]
Awesome. You're welcome. Have fun!
