### ISSUE TITLE
Errors not being returned when preceded by other result sets

### ISSUE THREAD

**Issue by lee-houghton** [w1nk/node-odbc#54]
It appears that if I run a query which returns some results, followed by an error, the error (and any subsequent result sets!) are not returned to the caller. The following code illustrates the problem (I'm using MS SQL 2012 Express):

``` javascript
var odbc = require('odbc')
var db = new odbc.Database()
var string = "(Connection string goes here)"

var sql =
"declare @t table (x int); \
insert @t values (1); \
select 'You will get this message' \
raiserror('You will never get this error!', 16, 100); \
select 'You will never get this message, either!' as msg; \
"

db.open(string, function(err) {
    console.log(err || "Connected")

    if (!err) {
        db.query(sql, function (err, results, more) {
            console.log(err, results, more)

            if (!more) {
                console.log("Running second query")

                db.query("select 1 as x", function(err, results, more) {
                    console.log(err, results, more)

                    db.close(function(err) { console.log(err || "Closed") })
                })
            }
        })
    }
})
```

I get the following output: 

```
Connected
null [] true
null [ { '': 'You will get this message' } ] false
Running second query
null [ { x: 1 } ] false
Closed
```

Where I would expect something like this:

```
Connected
null [] true
null [ { '': 'You will get this message' } ] true
{'message':'You will never get this error!'} [] true
null [ { msg: 'You will never get this message, either' } ] false
Running second query
null [ { x: 1 } ] false
Closed
```

Does this seem like a bug to you?

**Comment by lee-houghton** [comment]
Further info: I'm using MS SQL 2012 Express on Windows 8 (Driver={SQL Server Native Client 11.0}). Not tested with a Linux client.

I tried using ODBCResult and I got the same thing. 

I also tried connecting via ODBC using MS Access and I did get the error message, so it doesn't seem to be a problem with the ODBC driver.

**Comment by wankdanker** [comment]
Yes, it does seem like a bug. Thanks to your pull request, I should be able to get it fixed pretty quick.

Thanks,

Dan

**Comment by wankdanker** [comment]
Just pushed out v0.5.31 which contains your fixes. I elaborated on it a little bit so that several errors in a row are handled. And in the process I for the first time ever found a use for `finally` as in try/catch/finally. Lol.

Thank you for your help. Let me know if you find anything else or if this didn't really fix your issue.

Dan

**Comment by lee-houghton** [comment]
Good point about handling multiple errors; I hadn't thought of that!

I do now get an error returned, but sometimes the error comes back as a blank object (i.e. `{}`). It seems to behave differently depending on whether I run node with `--debug-brk` (in which case the error comes back correctly) or with `--debug` or no debug flag (blank error). 

I think this is due to the uninitialized `numfields` issue in `ODBC::GetSQLError` which I mentioned in my pull request. `SQLDiagGetField` was returning `SQL_ERROR`, and it turns out that you have to pass `0` as the record number when getting the error count, with MSSQL at least. Microsoft's documentation says that the record number is ignored if the requested field is a header field, but it doesn't seem that way. Pull request forthcoming...
