### ISSUE TITLE
no error when trying to query using a closed db connection

### ISSUE THREAD

**Issue by rbrcurtis** [w1nk/node-odbc#6]
I am expecting that I would get an error if I try to make a query using a closed connection, but I dont.  I'm using sql server 2008 using the freetds driver.

```
var db, odbc, sys;
sys = require("sys");
odbc = require("odbc");
db = new odbc.Database();
db.open("DRIVER={FreeTDS};SERVER=192.16.2.100;UID=user;PWD=pwd;DATABASE=db;TDS_Version=8.0;", function(err) {
  if (err != null) {
    throw err;
  }
  return db.close(function() {
    return db.query("select top 10 * from Users order by userid desc", function(err, rows, moreResultSets) {
      sys.debug("err:" + (sys.inspect(err)));
      sys.debug("rows:" + (sys.inspect(rows)));
      return sys.debug("more:" + (sys.inspect(moreResultSets)));
    });
  });
});
```

which outputs

```
DEBUG: err:null
DEBUG: rows:[]
DEBUG: more:false
```

**Comment by wankdanker** [comment]
Thanks rbcurtis, I'll take care of this.

**Comment by wankdanker** [comment]
Hi rbcurtis. I have pushed a fix for this in my fork : https://github.com/wankdanker/node-odbc

Try it out if you'd like. Otherwise I will run with this on my systems for a few days to test for issues before I push it here.

**Comment by rbrcurtis** [comment]
looks great, thanks!

**Comment by w1nk** [comment]
wankdanker, thanks for picking it up, I've been out of town.  I'll merge your fix in ASAP!

**Comment by wankdanker** [comment]
No problem. :) I'll send you a pull request.

**Comment by wankdanker** [comment]
Looks like w1nk merged my fix for this into master. So I'm going to close it. Thanks for reporting, rbrcurtis. :)

**Comment by rbrcurtis** [comment]
Thanks for fixing it so fast!

**Comment by w1nk** [comment]
No problem, forgot to mention that to you 2, sorry ;).
