### ISSUE TITLE
node.js, odbc, monetdb - varchar attributes all null

### ISSUE THREAD

**Issue by ahohl** [w1nk/node-odbc#60]
Friends of Code. I have a basic sample of odbc db lines running in node.js. Unfortunately for all db queries i make varchar attributes are reported as "null".

var db = require('odbc')()
  , cn = process.env.ODBC_CONNECTION_STRING
 ;

db.open(cn, function (err) {
if (err) return console.log(err);

db.query('select \* from users',  function (err, data) {
if (err) console.log(err);

console.log(data);

db.close(function () {
console.log('done');
});
});
});

Running this results as:

[ { name: null, fullname: null, default_schema: 2000 },
  { name: null, fullname: null, default_schema: 5899 } ]
done

While in monetdb it looks as follows:

+---------+---------------+----------------+
| name    | fullname      | default_schema |
+=========+===============+================+
| monetdb | MonetDB Admin |           2000 |
| wyh     | wyh analytics |           5899 |
+---------+---------------+----------------+

Any ideas??

**Comment by wankdanker** [comment]
Hi,

My gut instinct says to disable UNICODE. Try this from : https://github.com/wankdanker/node-odbc#unicode. 

In the `binding.gyp` file located in `node_modules/odbc`, change the section like:

``` json
'defines' : [
  "UNICODE"
],
```

to

``` json
'defines' : [
],
```

Then run `npm rebuild`. 

If this does not help, let me know what node-odbc version you have installed.

**Comment by ahohl** [comment]
Hi,
tried it out. Unfortunately no success so far. Now the simple sample code hangs on this query. other queries dont show different result. 
odbc version is 0.6.3 with dependency on bindings 1.0.0

Tx for the promt response.

**Comment by ahohl** [comment]
Can somebody report a set of versions of node, odbc and monetdb which reported to work as a starting base?

Tx

**Comment by wankdanker** [comment]
Hopefully someone will chime in, but you are the first person I have seen using monetdb with node-odbc. I started installing monetdb at home to try and debug this for you, but it's going to take some time.

**Comment by Pouja** [comment]
I have the same problem (node v0.10.23, node-gyp v0.13.0, MonetDB Database Server Toolkit v1.1 (Jan2014-SP1)).

Tried different built-in types of monetdb (varchar, char, string and text), each of them result in a null string. Also tried using UNICODE with and withouth, still the same result.

Edit: 
Here is an example of a debug line:
ODBC::GetColumnValue - String: index=6 name=wind type=-9 len=-1 value=Strong ret=100 bufferLength=1048575
It shows that somewhere from cpp char \* to javascript string the conversion fails.

**Comment by wankdanker** [comment]
Fix forthcoming.

**Comment by wankdanker** [comment]
`odbc@0.6.7` has been published including this fix. Closing. Please open a new issue if this does not fix your problem.
