### ISSUE TITLE
npm install odbc problems on CentOS 64bit

### ISSUE THREAD

**Issue by richschramm** [w1nk/node-odbc#62]
Trying to follow the wiki connection walk through examples and get the following errors in response to 'npm install odbc'   (Note I have already checked that the yum installs for unixODBC and unixODBC-devel say they are up to date and freetds seems to be working correctly also).

$ npm install odbc
npm http GET https://registry.npmjs.org/odbc
npm http 304 https://registry.npmjs.org/odbc

> odbc@0.6.5 preinstall /var/www/html/rovctd/node2solstice/node_modules/odbc
> node-gyp configure build

make: Entering directory `/var/www/html/rovctd/node2solstice/node_modules/odbc/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
../src/odbc.cpp: In static member function 'static v8::Handle<v8::Value> ODBC::GetColumnValue(void*, Column, uint16_t*, int)':
../src/odbc.cpp:450: error: expected primary-expression before '.' token
../src/odbc.cpp:451: error: expected primary-expression before '.' token
../src/odbc.cpp:452: error: expected primary-expression before '.' token
../src/odbc.cpp:453: error: expected primary-expression before '.' token
../src/odbc.cpp:454: error: expected primary-expression before '.' token
../src/odbc.cpp:455: error: expected primary-expression before '.' token
../src/odbc.cpp:456: error: expected primary-expression before '.' token
../src/odbc.cpp:457: error: expected primary-expression before '.' token
../src/odbc.cpp:458: error: expected primary-expression before '.' token
../src/odbc.cpp:459: error: expected primary-expression before '.' token
../src/odbc.cpp:460: error: expected primary-expression before '.' token
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
make: Leaving directory`/var/www/html/rovctd/node2solstice/node_modules/odbc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 2.6.32-431.11.2.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /var/www/html/rovctd/node2solstice/node_modules/odbc
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
$

**Comment by wankdanker** [comment]
Reverted 3cd95015 to fix this issue. v0.6.6 has been published.

Thanks,

Dan

**Comment by richschramm** [comment]
Excellent! Thank you for the very quick response.  For other newbies to git/node etc.... here is what worked for me:

1) Created a scratch directory to work in, cd into it
2) git clone git://github.com/wankdanker/node-odbc.git
3) cd to the resulting node-odbc sub-directory
4) git checkout 3cd9501      (git will print long warning about being in detached HEAD state - ignore)
5) cd back up to your scratch dir
6) now you can do the:   npm install odbc
7) continue on testing as per the walk-through

**Comment by rossipedia** [comment]
@richschramm if I may ask, which platform were you getting this error on?

**Comment by richschramm** [comment]
CentOS release 6.5 (Final)
Kernel 2.6.32-431.11.2.el6.x86_64 on an x86_64

**Comment by rossipedia** [comment]
lol... guess I should've read the title :)
