### ISSUE TITLE
[IBM-DB2] Returns error object with no properties from a simple query.

### ISSUE THREAD

**Issue by leodutra** [w1nk/node-odbc#64]
Executing a simple `.query('select * from table' [...])` returns an error object with no property, not even code or description.

Although, It does send me a complete error object when there's a bad configuration on `.open` or most of driver exceptions occur.

I'm working on a spare time project and got no time and tools now to debug the core. Sorry.

Issue registered, incomplete but waiting for more information.
Thank you for the good work.

**Comment by leodutra** [comment]
FYI, @wankdanker, @bretcope. Hope I can help you guys soon. 
Very nice job.

**Comment by wankdanker** [comment]
Hey @LeoDutra,

I think I can replicate this with the following query:

``` js
db.query('select * from table where id = ?', console.log);
```

outputs

``` js
{} [] false
```

Whereas

``` js
db.query('select * from table where id = 1', console.log);
```

outputs

``` js
{ error: '[node-odbc] SQL_ERROR',
  message: '[FreeTDS][SQL Server]Invalid column name \'id\'.',
  state: '42S22' } [] false
```

Is this what you are experiencing?

**Comment by leodutra** [comment]
Yes, although There's no `where` clause nor signs like `?`.

I don't think it is a encoding problem... I think. Did a small test over this possibility.

**Comment by leodutra** [comment]
It was more exactly a query like this (project is not here in my home):

`select * from dbprod.some_table_name`

**Comment by wankdanker** [comment]
Based on what I've been able to replicate it seems like in some cases with some drivers, an error may occur but no diagnostic data is available to `SQLGetDiagRec`. In cases where there was no data available from `SQLGetDiagRec` an empty error object was being returned.

I have added an additional check for this and now return a generic error object indicating that an error has occurred but there is no diagnostic information available.

If you want to test it before I release it, install from my repo with `npm install wankdanker/node-odbc`.

**Comment by leodutra** [comment]
This is the IBM driver:
`IBM Data Server Client version 10.5 fix pack 3 Windows nt_x64`. 
It's the latest now (may/2014).

**Comment by wankdanker** [comment]
I pushed out v0.6.7 to npm which includes the generic error message if no diagnostic information can be found. Try it out. 

I don't have a DB2 setup to experiment with.

Is there something actually wrong with the query you are executing? Can you get any query to execute properly?
