### ISSUE TITLE
When 2 (or more) tables got the same column name, only one is being returned.

### ISSUE THREAD

**Issue by leodutra** [w1nk/node-odbc#66]
Example:

``` sql
SELECT  A.X,
        B.X
FROM TABLE_A A, 
     TABLE_B B
```

Returns only one columns `X` data (wrong).
**MUST** return both `A.X` and `B.X`.

_A reminder:_ JavaScript objects work as a kind of hashset. It's not possible to have 2 properties with the same name.

**Comment by wankdanker** [comment]
Right. See my response in #65
