### ISSUE TITLE
dynodbc and 0.6.8

### ISSUE THREAD

**Issue by amcintyre99** [w1nk/node-odbc#67]
changing to dynodbc gets this
https://gist.github.com/amcintyre99/d4ba9482460c8261b574

dropping back to 0.6.7 and all is good... well, except for the usual dynodbc related compiler warnings
https://gist.github.com/amcintyre99/290b6127222341cac70e

and thanks!!! using your module every day!!!

**Comment by wankdanker** [comment]
Cool, thanks for the report. Are you using the module with UNICODE disabled? Looks like a simple syntax error that hits only when UNICODE is disabled. I'll get that fixed next time I'm at a computer. :)

**Comment by amcintyre99** [comment]
i could never get both dynodbc and unicode to compile at the same time, one or the other but not both, so i stuck with dynodbc since it's much faster

if you have a suggestion for how to code both in binding.gyp, i will give it a try

**Comment by amcintyre99** [comment]
all good with 0.6.9 and dynodbc

thanks!!!

**Comment by wankdanker** [comment]
Great. Glad to hear. Have a good one!
