### ISSUE TITLE
Cannot connect to Vertica on v0.6.10

### ISSUE THREAD

**Issue by petermikitsh** [w1nk/node-odbc#68]
Somewhere between version 0.6.6 and 0.6.10 the ability to connect to Vertica broke.

The code: 

```
this.db.open(this.connection_string, function (err) {
    if (err) {
      console.log('An error occured connecting to Vertica.');
    }
    callback(err);
});
```

With identical configurations, I observe the following values for `err` in the callback:

Version 0.6.6:

```
undefined
```

Version 0.6.10:

```
error: "[node-odbc] SQL_ERROR"
message: "[unixODBC]["
state: "H"
```

**Comment by wankdanker** [comment]
Any chance you could compile v0.6.10 with the DEBUG flag in binding.gyp and run your test?

**Comment by wankdanker** [comment]
Here's the diff between 0.6.6 and 0.6.10 : https://github.com/wankdanker/node-odbc/compare/v0.6.6...v0.6.10

**Comment by petermikitsh** [comment]
I re-ran `npm install` but forgot to remove the requires 'UNICODE' line in binding.gyp and rebuild after (required for Vertica). I've done that this time and the error went away. All is good here.

**Comment by wankdanker** [comment]
Cool. Glad to hear. I'm thinking about making the UNICODE option a runtime configuration thing. Having to set a compile-time flag is pretty clumsy.

**Comment by petermikitsh** [comment]
I agree-- if possible, it would be more convenient to supply at runtime.

Thanks for your help and your work on the node-odbc project, btw. It's a very useful package.
