### ISSUE TITLE
Might not be working for Windows 64-bit?

### ISSUE THREAD

**Issue by bzuillsmith** [w1nk/node-odbc#71]
Can anyone confirm this? I've been using this library on my 32-bit Windows 7 machine to directly access MS Access .mdb files for a data migration tool my company is building. Works fine for that machine, but tried it on two machines yesterday and they got an error complaining that the file could not be found and the driver was not specified (something like that). Each was Windows 7 64-bit and Windows 8 64-bit. I got no compile errors during install, just a few warnings which is usual for node-gyp on Windows.

The connection string I'm using:
`Driver={Microsoft Access Driver (*.mdb, *.accdb)};Dbq=' + path + ';'` Path definitely exists for each. I used `fs` to confirm. Any ideas?

I might post the output of the installs when I get them from my colleague.

**Comment by wankdanker** [comment]
Out of curiosity, could you try setting up a system DSN for the database (or a database) and try using DSN=dsnname in your connection string?

It's possible that the `fs` module doesn't resolve `path` the same way that the Microsoft Access Driver resolves paths. Are you using a relative path or an absolute path?

**Comment by bzuillsmith** [comment]
I'm using an absolute path. Both / and \ work for the path string on my Win 32-bit. When I get the chance, I'll try the DSN route on one of the systems having the issue.

**Comment by wankdanker** [comment]
If the file paths work on 32bit, then I'd expect them to work on 64bit too. It seems more likely that something else is going wrong. I have compiled this on Windows 64bit (Server 2008) and it worked against SQL server using a DSN. But, that was several versions back. 

You could always try enabling debugging:

https://github.com/wankdanker/node-odbc#debug

And disable UNICODE:

https://github.com/wankdanker/node-odbc#unicode

**Comment by bzuillsmith** [comment]
This actually appears to be a Windows Access Driver issue on 64-bit systems. The Driver appears on a list of available ODBC datasources in Windows but when you click 'configure' it is then revealed the the Driver doesn't appear to be around and needs to be reinstalled _sigh_. I'm working to install them and confirm that is the issue. I'll let you know.

**Comment by bzuillsmith** [comment]
Indeed, this is an annoying windows driver issue. For anyone else who comes across this: It seems to require the Microsoft Access Database Engine 2010 Redistributable (x64) at http://www.microsoft.com/en-us/download/details.aspx?id=13255
This is because the 32-bit ODBC Windows drivers don't work with 64-bit applications.

**Comment by wankdanker** [comment]
Glad you figured it out. Thank you for following up.

**Comment by CoDEmanX** [comment]
@wankdanker:

> I have compiled this on Windows 64bit (Server 2008)

Could you provide Windows builds for node-odbc / unixODBC? Or is there any trouble with the law to offer them? Compiling software on on Windows is often a pain and rather uncommon (it's usually plug'n'pray).

**Comment by wankdanker** [comment]
Hey @CoDEmanX,

I understand the inconvenience for Windows users. Unfortunately, I am still unaware of any mainstream npm based build and distribution process for compiled modules. I currently do not have the time or resources to build for different combinations of node and Windows. 

I only test building on a Windows 2008 server, and that is rare when I do that. If I were to bundle that single compilation up, it would probably still be plug'n'pray for anyone who uses it. 

So, the trouble is not with the law (as far as I'm aware), the trouble is with infrastructure. Now, I haven't been paying attention to the Windows side of things lately, so maybe there have been some developments with generating Windows builds via some 3rd party platform or something. If that is the case and someone can let me know about it, I can look into getting that going. 

But, doing one-off compiles is something that I can not commit to. :(

Dan

**Comment by CoDEmanX** [comment]
I see, it shouldn't cost you a lot valuable time of course!

http://stackoverflow.com/a/19705293/2044940 suggests to use [node-gyp](https://github.com/TooTallNate/node-gyp), maybe that's such a build system?

**Comment by wankdanker** [comment]
We use node-gyp (by way of the `bindings.gyp` file) which simplifies the build process on Windows (and all platforms). If you have the proper build environment set up on Windows, you can just run `npm install odbc` and it will use node-gyp to run the build process. So, that works. 

What we need is an automated way to to run node-gyp on multiple versions of windows against multiple versions of node, save the compiled modules and then distribute them somehow.
