### ISSUE TITLE
How about connection lost?

### ISSUE THREAD

**Issue by aydn** [w1nk/node-odbc#73]
``` javascript
// https://www.npmjs.org/package/odbc
var odbc = require("odbc");

module.exports = function(conf)
{
    var link = 'DRIVER={' + conf.driver + '};HOST=' + conf.host + ';PORT=' 
        + conf.port + ';UID=' + conf.user + ';PWD=' + conf.password + ';DB=' + conf.database;

    var db = new odbc.Database();
    var self = this;

    self.connect = function connect(callback) {
        db.open(link, callback);
    };

    self.close = function close(callback) {
        db.close(callback);
    };

   /*
       After connection, can I reuse the 'db' obj. for each query?
       Or should I connect / query / close for each query?
       If we have not to connect / close for each query, how can I detect the connection status?
       I need something like that in my opinion,
              db.on('close', reconnect) etc..
       Do I need?
   */
}
```

**Comment by nevercast** [comment]
I believe there is db.connected, I've not looked in to events. 
Yes you can use one connection for all the queries, and close when your program is finished, or you can open and close every time. Both will work.

**Comment by wankdanker** [comment]
There are no events emitted for when the database connection is closed. 

As @nevercast said, you can check `db.connected` to see if a connection was previously successfully opened and not yet closed. However, it will not indicate if the server has gone down or there has been a network error. Your best bet is to just execute a query and handle any errors you get.

And yep, you can re-use a single `db` instance without closing/reopening. And it will attempt to queue your queries.
