### ISSUE TITLE
You've force pushed over commits and orphaned them

### ISSUE THREAD

**Issue by nevercast** [w1nk/node-odbc#75]
SHAs such as bbf20a123d49666d55de68e3de4e15808849a021 and c0316d785a478ea30a9fd80c95d4f253c89ebd1e are orphaned, visible on Github but cannot be checked out. You need to checkout the latest SHA you have (Look through reflog) and create a branch for it or fast-forward master to it.

I am unable to get the source code for anything newer than version 1.3 due to the broken references.

**Comment by wankdanker** [comment]
What repo are you cloning or pulling from? w1nk's repo is pretty out of date (v0.3.1). My repo (git://github.com/wankdanker/node-odbc.git) has the most recent code. If you are talking about my repo then I'm sorry for the mistake and I'll try to get it resolved. I did clone my repo into a empty dir and it had the two commits you mentioned.

**Comment by nevercast** [comment]
Ahhh sweet sweet commits!
I wasn't aware of your repo, somehow I've been constantly linked to this one and since I couldn't find the commit messages but the SHAs still worked I'd assumed the references were all broken. I must have been really tired because I even sent an email to Github stuff asking them if they could reflog my fork.

I'll be sure to pull from your one, cheers!
