### ISSUE TITLE
node-odbc is sending least relevant error data back for Microsoft drivers

### ISSUE THREAD

**Issue by bzuillsmith** [w1nk/node-odbc#83]
I noticed Microsoft drivers tend to send back multiple Error records for things such as a bad connection string. The first is often most relevant, and the following are sub-errors.

Right now node-odbc returns the `state` of the last  error in the list, but the first error is actually the primary error (for Micorsoft at least) and most helpful and relevant at times. Is it the same for unix-based systems?

Also, the `message` field of the error object is a concatenated string of all the errors, however the Error prototype added to the object is not. Instead, it is the message of the last error in the list.

https://github.com/wankdanker/node-odbc/blob/master/src/odbc.cpp#L848-L875

**Comment by bzuillsmith** [comment]
Pull request submitted https://github.com/wankdanker/node-odbc/pull/14

**Comment by wankdanker** [comment]
Fixed in v1.1.0. Thank you.
