### ISSUE TITLE
SQL_INVALID_HANDLE after quick update and read

### ISSUE THREAD

**Issue by bzuillsmith** [w1nk/node-odbc#88]
I hit this assertion in my program and it fails: https://github.com/wankdanker/node-odbc/blob/master/src/odbc.cpp#L597

I'm opening a connection to an MSAccess doing and update, then closing it. Right after, I open another connection and read entire tables. During these reads, I often hit the assertion. It only seems to happen if any rows are modified (sometimes the update has no effect). It happens most times, but not  every time.

It is some kind of race condition. Outputting the full debug logs makes it go slower and I never land on the assertion. Also I never hit it if I don't do an update first. I put a fprintf just before the assertion (Release mode) and got:

```
ODBC::GetColumnValue - String: index=22 name=s type=-9 len=0 value= ret=-2 bufferLength=1048575
```

This could easily be an MSAccess driver or db issue because it's a pretty terrible db, still investigating though. Yay for legacy systems.

**Comment by wankdanker** [comment]
Curious how your code looks for this. Are you using two different instances of odbc for reading and writing? Or are you using one instance and opening/closing it?

ie:

``` js
var odbc = require('odbc');
var reader = odbc();
var writer = odbc();

writer.open(cs, function (err) {
    writer.query('update ...', function (err, data) {
        writer.close(function (err) {
            reader.open(cs, function (err) {
                reader.query('select * from ...', function (err, data) {

                });
            });
        });
    });
});
```

**Comment by bzuillsmith** [comment]
Yeah, two different instances. Your example is pretty much equivalent.  Seems like a driver issue because it never stops in the same place. Sometimes it just hangs without giving any error. Gonna keep stabbing away at it.

**Comment by bzuillsmith** [comment]
Just fyi, this is a more detailed summary of my code.

``` javascript
var writer = odbc();
writer.open(cs, function (err) {

    // A series of calls like this
    writer.beginTransactionSync();
    var stmt = writer .prepareSync('UPDATE ...');
    var count = stmt.executeNonQuerySync();
    ...
    writer.commitTransactionSync();

    writer.close(callback)
});
```

``` javascript
// shortly after the callback for the writer is called
var reader = odbc();
reader.open(cs, function (err) {
    // This is simplified. All queries are called async and waited on by the Q library using q.spread
    // (I wrap each for the Q promise api)
    reader.query('select * from ...', cb);
    reader.query('select * from ...', cb);
    ...
    // when all have returned data, a function is called with the close operation
    reader.close(callback);
});
```

**Comment by wankdanker** [comment]
I wonder if calling `stmt.closeSync()` before `writer.close(...)` would have a positive effect.

**Comment by bzuillsmith** [comment]
Ahah! I had no idea they needed to be closed. Seems to be working fine now. I guess references to those statements must have been floating about somewhere and causing problems?

**Comment by bzuillsmith** [comment]
Hard to tell what was happening because of the unclosed statements. I'm using Electron (similar to WebKit) and I am not sure how to have it give me a good crash report in this instance. That assertion error wasn't coming through any try/catch. It seemed to partially crash the program.

**Comment by wankdanker** [comment]
I never implemented any sort of open object tracking on the JS side to implicitly close un-closed objects (such as statements) when the connection is closed. I assumed that ODBC would handle that in C land. I guess I was wrong!

I would have thought that would just lead to a memory leak though. I don't understand why one of those statement references would end up in `GetColumnValue`!

Yeah, that assert is in C++ land and I think those should cause node/Electron to crash. Probably without a stack trace (from JS anyway). Your C/C++ debugger might be able to though.

**Comment by bzuillsmith** [comment]
Makes sense. Yeah, I would have thought it would just me memory leak too. It could be that the driver just croaked while my select queries were happening. It never stopped at the same place and I had a couple crashes that didn't seem to happen in the GetColumnValue at all. A couple times it just hung like it was waiting for a response. I'm curious to see the behavior with other drivers, but not curious enough to do it right now :P ha!

**Comment by wankdanker** [comment]
Curious if the issue would happen after the process was running for a while or if it happened right off the bat. If it was after a while, ODBC might have run out of statement handles or something.

Anyhow, glad it's working now. :)
