### ISSUE TITLE
is this nan 2.0.0 related? which was published 7/31

### ISSUE THREAD

**Issue by amcintyre99** [w1nk/node-odbc#92]
$ npm install odbc
\

> odbc@1.1.6 install /home/andrew/dma/prd/node_modules/odbc
> node-gyp configure build

make: Entering directory `/home/andrew/dma/prd/node_modules/odbc/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
../src/odbc.cpp: In static member function ‘static void ODBC::New(const v8::FunctionCallbackInfov8::Value&)’:
../src/odbc.cpp:143:34: error: call of overloaded ‘NanThrowError(v8::Localv8::Object&)’ is ambiguous
     return NanThrowError(objError);
                                  ^
../src/odbc.cpp:143:34: note: candidates are:
In file included from ../src/odbc.h:23:0,
                 from ../src/odbc.cpp:25:
../node_modules/nan/nan.h:705:21: note: void NanThrowError(v8::Handlev8::String)
     NAN_INLINE void NanThrow ## NAME(v8::Handlev8::String errmsg) {          \
                     ^
../node_modules/nan/nan.h:711:3: note: in expansion of macro ‘X’

**Comment by amcintyre99** [comment]
yep, did a clone and changed package.json nan to 1.8.4 and all good

**Comment by bzuillsmith** [comment]
Thanks, just submitted a pull request with a hot fix. Seems nan broke something before their major version change.

**Comment by wankdanker** [comment]
Thank you both! Published v1.1.7 to npm.
