### ISSUE TITLE
Update for nan 2.0 API changes (io.js 3.x - node.js 4.0)

### ISSUE THREAD

**Issue by leodutra** [w1nk/node-odbc#93]
nan was updated to 2.0 and supports V8 changes in io.js 3.x.

This new API will be determinant for [node.js 4.0](https://github.com/nodejs/node/issues/2522)

**Comment by bzuillsmith** [comment]
Yep, just need someone to get it compiling with 2.0.

**Comment by LeoDutra** [comment]
I'm newbie on C++, but I'll try...


*Leo Dutra, **on **Facebook <http://www.facebook.com/leodutra.br>
**and LinkedIn
<https://www.linkedin.com/profile/view?id=43944294>*

2015-08-27 20:15 GMT-03:00 Ben Zuill-Smith <notifications@github.com>:

**Comment by leodutra** [comment]
Temporary fix: restrict supported node engine on `package.json` (https://github.com/deckar01/node-odbc/commit/24b4e0b1731233c57e397f9c0bb24709c33642c5).

**Comment by wankdanker** [comment]
Just released odbc@1.2.0 which compiles and passes tests with current nan and node@0.8.28, node@0.10.40, node@0.12.7, node@4.0.0, node@4.1.0, node@4.1.1 but has not been extensively tested for memory leaks or things of that nature.

**Comment by leodutra** [comment]
A whole day running SQL on [BlazingSquirrel](https://github.com/LeoDutra/blazing-squirrel) web SQL client.

No signal of memory leaks serving on Ubuntu 14.04.3 with IBM DB2 CLI Driver 10.x. And I'm talking about more than 10 million registers at least.

Awesome, Dan.

**Comment by wankdanker** [comment]
Awesome. Glad to hear it!
