### ISSUE TITLE
Build fails on node v4.x

### ISSUE THREAD

**Issue by deckar01** [w1nk/node-odbc#94]
**Issue**
`node-gyp` fails to build `odbc_result.cpp` on `node v4.x`.

**Cause**
#93 Seems to identify part of the problem, v4.x `NAN` changes are not supported yet, although there may be other breaking changes.

**Expected Behavior**
The [node engine version](https://docs.npmjs.com/files/package.json#engines) should be configured in `package.json` to prevent `npm` from trying build and to generate a useful error message.

**Comment by wankdanker** [comment]
Added node < 4.0.0 restriction in package.json in v1.1.8 on npm.

Thank you.
